ktor:
    # Known issue where developemnt mode breaks graphql kotlin codegen.
    # https://github.com/ExpediaGroup/graphql-kotlin/issues/1543
    # May be fixed, or the error may be hidden by a TypeNotSupported Exception...
    development: false
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
